#+TITLE: Doom personal configuration

* Contents :TOC_3:noexport:
- [[#doom-bootstrap][doom bootstrap]]
  - [[#personal-data][Personal data]]
  - [[#set-up-theme][Set up theme]]
  - [[#line-numbers][Line numbers]]
  - [[#org-directory][Org directory]]
- [[#ui-configuration][UI Configuration]]
  - [[#doom-themes][Doom-themes]]
  - [[#doom-modeline][Doom-modeline]]
  - [[#fonts][Fonts]]
- [[#tasks-16][Tasks]]

* doom bootstrap

** Personal data
Personal information for file templates and snippets
#+begin_src emacs-lisp
(setq user-full-name "nolo18"
      user-mail-address "nolo18@khelnet.xyz")
#+end_src

** Set up theme
#+begin_src emacs-lisp
(setq doom-theme 'doom-tomorrow-night)
#+end_src

** Line numbers

#+begin_src emacs-lisp
(setq display-line-numbers-type t)
#+end_src

I don't want line numbers in some modes.

#+begin_src emacs-lisp
;; TODO: This not working.

(after! 'org
       (remove-hook 'org-mode-hook 'display-line-numbers))
#+end_src


** Org directory
If you use `org' and don't want your org files in the default location below,
change `org-directory'. It must be set before org loads!
=(setq org-directory "~/org/"=

* UI Configuration

** Doom-themes

[[https://github.com/hlissner/emacs-doom-themes][doom-themes]] has a lot of configuration options. Some of them are no obvious.

#+begin_src emacs-lisp
(after! 'doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italics t))
#+end_src

** Doom-modeline
I want to configure some aspects of doom modeline.

Maybe I want modeline be smaller I found this on its github page.
#+begin_comment
(setq doom-modeline-height 1)
(set-face-attribute 'mode-line nil :family "Noto Sans" :height 100)
(set-face-attribute 'mode-line-inactive nil :family "Noto Sans" :height 100)
#+end_comment


#+begin_src emacs-lisp
(after! doom-modeline
  (setq doom-modeline-major-mode-icon t
        doom-modeline-major-mode-color-icon t
        doom-modeline-height 1)
  (set-face-attribute 'mode-line nil :height 95)
  (set-face-attribute 'mode-line-inactive nil :height 95))
#+end_src

** Fonts
 Doom exposes five (optional) variables for controlling fonts in Doom. Here
 are the three important ones:

 + `doom-font'
 + `doom-variable-pitch-font'
 + `doom-big-font' -- used for `doom-big-font-mode'; use this for
   presentations or streaming.

   _Note:_ enabling bold and italics font was made via [[Doom-themes][Doom-themes]] configuration.

 #+begin_src emacs-lisp
(setq doom-font "DejaVuSansMono Nerd Font Mono 11"
      doom-variable-pitch-font "DejaVuSansMono Nerd Font Mono 11"
      doom-big-font "DejaVuSansMono Nerd Font Mono 18")

;; TODO: Comments doesn't shows in italics
(set-face-attribute 'font-lock-comment-face nil :slant 'italic)

#+end_src

* TODO Tasks [1/6]
- [-] Organize this file [1/2]
  + [ ] Set up all labels in the heading.
  + [X] Maybe create a table of content.
- [ ] Set all doom fonts correctly.
- [-] Org [0/4]
  + [ ] Get bigger headlines size
  + [ ] Install org-bullets
  + [-] Take a look org-mode-hook and remove some hooks. I need to find the way to acomplish this.
  + [ ] Configure org-variables (org-hide-emphasis-makers & friends)
- [-] Doom-Modeline [0/2]
  + [-] Set smaller size
  + [ ] Get rid about flycheck icon when not running.
- [X] Doom-themes [1/1]
  + [X] Configure doom-themes variables
- [ ] Doom big font mode doesn't work
