#+TITLE: Doom personal configuration
#+AUTHOR: nolo18
#+EMAIL: nolo18@khelnet.xyz
#+DESCRIPTION: Personal configuration layer on top of Doom-emacs defaults.
#+STARTUP: showall


* Contents :TOC_2:noexport:
- [[#doom-bootstrap][Doom bootstrap]]
  - [[#lexican-binding][Lexican binding]]
  - [[#personal-data][Personal data]]
  - [[#set-up-theme][Set up theme]]
  - [[#line-numbers][Line numbers]]
- [[#ui-configuration][UI Configuration]]
  - [[#doom-themes][Doom-themes]]
  - [[#doom-modeline][Doom-modeline]]
  - [[#fonts][Fonts]]
- [[#org-mode][Org-mode]]
  - [[#org-appareance][Org appareance]]
  - [[#org-directory][Org directory]]
  - [[#org-mode-hook][Org-mode hook]]
- [[#keybindings][Keybindings]]
  - [[#smartparens][smartparens]]
- [[#need-to-be-moved][Need to be moved]]
  - [[#smartparens-strict-mode][smartparens strict mode]]
- [[#tasks-00][Tasks]]

* Doom bootstrap

** Lexican binding
I found an error with doom variables if lexical-binding is not define

#+begin_src emacs-lisp
;;; -*- lexical-binding: t -*-
#+end_src

** Personal data
Personal information for file templates and snippets
#+begin_src emacs-lisp
(setq user-full-name "nolo18"
      user-mail-address "nolo18@khelnet.xyz")
#+end_src

** Set up theme
#+begin_src emacs-lisp
(setq doom-theme 'doom-tomorrow-night)
#+end_src

** Line numbers

#+begin_src emacs-lisp
(setq display-line-numbers-type t)
#+end_src


* UI Configuration

** Doom-themes

[[https://github.com/hlissner/emacs-doom-themes][doom-themes]] has a lot of configuration options. Some of them are no obvious.

#+begin_src emacs-lisp
(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italics t))
#+end_src

Matching pair highlight is not easy to see. Customization using =custom-set-face!= doom macro for avoiding load order issues

#+begin_src emacs-lisp
(custom-set-faces!
  '(show-paren-match :inverse-video t))
#+end_src


** Doom-modeline
I want to configure some aspects of doom modeline.

#+begin_src emacs-lisp
(after! (doom-modeline doom-themes)
  (setq doom-modeline-major-mode-icon t
        doom-modeline-major-mode-color-icon t
        doom-modeline-height 1))
#+end_src

** Fonts
 Doom exposes five (optional) variables for controlling fonts in Doom. Here
 are the three important ones:

 + `doom-font'
 + `doom-variable-pitch-font'
 + `doom-big-font' -- used for `doom-big-font-mode'; use this for
   presentations or streaming.

   _Note:_ enabling bold and italics font was made via [[Doom-themes][Doom-themes]] configuration.

 #+begin_src emacs-lisp
(setq doom-font (font-spec :family "SauceCodePro Nerd Font Mono" :size 16 :weight 'regular)
      doom-variable-pitch-font (font-spec :family "SauceCodePro Nerd Font Mono")
      doom-big-font (font-spec :family "SauceCodePro Nerd Font Mono" :size 18 :weight 'regular))
#+end_src

* Org-mode

** Org appareance

Use org-bullets to change stars for a clean rounded circle.

#+begin_src emacs-lisp
(use-package! org-bullets
  :after org
  :hook (org-mode . org-bullets-mode)
  :config
  (setq org-bullets-bullet-list '("◉" "○"))
  )
#+end_src

After load org, I want to make some tweaks to org apareance:
+ Make headlines from level 1 to 4 bigger than normal text.
+ Change org-ellipsis for anything more visual than 3 dots.
+ Hide emphasis markers to make more readable the text.
+ Positioning tags at the right.

#+begin_src emacs-lisp
(after! org
  (set-face-attribute 'org-document-title nil :height 1.6)
  (set-face-attribute 'org-level-1 nil :height 1.4)
  (set-face-attribute 'org-level-2 nil :height 1.3)
  (set-face-attribute 'org-level-3 nil :height 1.2)
  (set-face-attribute 'org-level-4 nil :height 1.1)

  ;; hide emphasis markers
  (setq org-hide-emphasis-markers t)

  ;; set org ellipsis for something more visual
  (setq org-ellipsis "⬎")

  ;; Positioning tags at the right
  (setq org-tags-column -77))

#+end_src

** Org directory
If you use `org' and don't want your org files in the default location below,
change `org-directory'. It must be set before org loads!

#+begin_src emacs-lisp
(if (file-directory-p "/mnt/NASshare/org")
    (setq org-directory "/mnt/NASshare/org"
          org-agenda-files (list org-directory))
  (setq org-directory nil))
#+end_src


** Org-mode hook

Doom apply some minor modes globally. Some of them has no sense in orgmode. So It will be necesary to make a custom function to disable or enable some predefined stuff in doom.

#+begin_src emacs-lisp
;;(defun nolo18/org-mode-hook ()
;;  (progn
;;    (display-line-numbers-mode 0)
;;    (flycheck-mode nil)))

(add-hook 'org-mode-hook (lambda () (display-line-numbers-mode 0) (flycheck-mode 0)))
#+end_src



* Keybindings

Some global preconfigured keys which i don't ever use, disturb some personal preferences, so I better disable them.

#+begin_src emacs-lisp
(global-unset-key (kbd "<C-right>"))
(global-unset-key (kbd "<C-left>"))
(global-unset-key (kbd "<C-M-right>"))
(global-unset-key (kbd "<C-M-left>"))
#+end_src

** smartparens
Some interesting functions for smartparens has no defined keybinding. I'm going to change that.

#+begin_src emacs-lisp
(define-key smartparens-mode-map (kbd "<C-right>") 'sp-forward-slurp-sexp)
(define-key smartparens-mode-map (kbd "<C-left>") 'sp-forward-barf-sexp)
(define-key smartparens-mode-map (kbd "<C-M-right>") 'sp-backward-slurp-sexp)
(define-key smartparens-mode-map (kbd "<C-M-left>") 'sp-backward-barf-sexp)
#+end_src


* TODO Need to be moved
Some configurations which I don't really know where to put.

** smartparens strict mode
I like to have smartparens strict mode in all lisp type of languages.

#+begin_src emacs-lisp
(add-hook! '(lisp-mode-hook
             emacs-lisp-mode-hook
             sly-mrepl-mode-hook
             lisp-interaction-mode) 'smartparens-strict-mode)
#+end_src

* TODO Tasks [0/0]
