#+TITLE: Doom personal configuration
#+AUTHOR: nolo18
#+EMAIL: nolo18@khelnet.xyz
#+DESCRIPTION: Personal configuration layer on top of Doom-emacs defaults.
#+STARTUP: showall


* Contents :TOC_2:noexport:
- [[#doom-bootstrap][Doom bootstrap]]
  - [[#lexican-binding][Lexican binding]]
  - [[#personal-data][Personal data]]
  - [[#set-up-theme][Set up theme]]
  - [[#line-numbers][Line numbers]]
- [[#ui-configuration][UI Configuration]]
  - [[#doom-themes][Doom-themes]]
  - [[#doom-modeline][Doom-modeline]]
  - [[#fonts][Fonts]]
- [[#org-mode][Org-mode]]
  - [[#org-appareance][Org appareance]]
  - [[#org-directory][Org directory]]
  - [[#org-mode-hook][Org-mode hook]]
- [[#tasks-17][Tasks]]

* Doom bootstrap

** Lexican binding
I found an error with doom variables if lexical-binding is not define

#+begin_src emacs-lisp
;;; -*- lexical-binding: t -*-
#+end_src

** Personal data
Personal information for file templates and snippets
#+begin_src emacs-lisp
(setq user-full-name "nolo18"
      user-mail-address "nolo18@khelnet.xyz")
#+end_src

** Set up theme
#+begin_src emacs-lisp
(setq doom-theme 'doom-tomorrow-night)
#+end_src

** Line numbers

#+begin_src emacs-lisp
(setq display-line-numbers-type t)
#+end_src


* UI Configuration

** Doom-themes

[[https://github.com/hlissner/emacs-doom-themes][doom-themes]] has a lot of configuration options. Some of them are no obvious.

#+begin_src emacs-lisp
(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italics t))
#+end_src

** Doom-modeline
I want to configure some aspects of doom modeline.

#+begin_src emacs-lisp
(after! (doom-modeline doom-themes)
  (setq doom-modeline-major-mode-icon t
        doom-modeline-major-mode-color-icon t
        doom-modeline-height 1))
#+end_src

** Fonts
 Doom exposes five (optional) variables for controlling fonts in Doom. Here
 are the three important ones:

 + `doom-font'
 + `doom-variable-pitch-font'
 + `doom-big-font' -- used for `doom-big-font-mode'; use this for
   presentations or streaming.

   _Note:_ enabling bold and italics font was made via [[Doom-themes][Doom-themes]] configuration.

 #+begin_src emacs-lisp
(setq doom-font "SauceCodePro Nerd Font Mono 11"
      doom-variable-pitch-font "SauceCodePro Nerd Font Mono 11"
      doom-big-font "SauceCodePro Nerd Font Mono 11")
#+end_src

* Org-mode

** Org appareance

Use org-bullets to change stars for a clean rounded circle.

#+begin_src emacs-lisp
(use-package! org-bullets
  :after org
  :hook (org-mode . org-bullets-mode)
  :config
  (setq org-bullets-bullet-list '("◉"))
  )
#+end_src

After load org, I want to make some tweaks to org apareance:
+ Make headlines from level 1 to 4 bigger than normal text.
+ Change org-ellipsis for anything more visual than 3 dots.
+ Hide emphasis markers to make more readable the text.
+ Positioning tags at the right.

#+begin_src emacs-lisp
(after! org
  (set-face-attribute 'org-document-title nil :height 1.6)
  (set-face-attribute 'org-level-1 nil :height 1.4)
  (set-face-attribute 'org-level-2 nil :height 1.3)
  (set-face-attribute 'org-level-3 nil :height 1.2)
  (set-face-attribute 'org-level-4 nil :height 1.1)

  ;; hide emphasis markers
  (setq org-hide-emphasis-markers t)

  ;; set org ellipsis for something more visual
  (setq org-ellipsis "⬎")

  ;; Positioning tags at the right
  (setq org-tags-column -77))

#+end_src

** Org directory
If you use `org' and don't want your org files in the default location below,
change `org-directory'. It must be set before org loads!

#+begin_src emacs-lisp
(if (file-directory-p "/mnt/NASshare/org")
    (setq org-directory "/mnt/NASshare/org"
          org-agenda-files (list org-directory))
  (setq org-directory nil))
#+end_src


** Org-mode hook

Doom apply some minor modes globally. Some of them has no sense in orgmode. So It will be necesary to make a custom function to disable or enable some predefined stuff in doom.

#+begin_src emacs-lisp
;;(defun nolo18/org-mode-hook ()
;;  (progn
;;    (display-line-numbers-mode 0)
;;    (flycheck-mode nil)))

(add-hook 'org-mode-hook (lambda () (display-line-numbers-mode 0) (flycheck-mode 0)))
#+end_src

* TODO Tasks [1/7]
- [-] Organize this file [1/2]
  + [ ] Set up all labels in the heading.
  + [X] Maybe create a table of content.
- [ ] Set all doom fonts correctly.
- [-] Org [3/4]
  + [X] Get bigger headlines size
  + [X] Install org-bullets
  + [X] Disable line-numbers in org-mode
  + [-] Configure org-variables (org-hide-emphasis-makers & friends)
- [-] Doom-Modeline [1/2]
  + [-] Set smaller size
  + [ ] Get rid about flycheck icon when not running.
- [X] Doom-themes [1/1]
  + [X] Configure doom-themes variables
- [ ] Doom big font mode doesn't work
- [ ] Maybe will be a good idea to store personal data in a separate file and load it.
